### ISSUE TITLE
Firming up Connection

### ISSUE THREAD

**Issue by hamiltop** [hamiltop/rethinkdb-elixir#10]
Connection driver should support:

1. Supervision
2. Can be connection pooled if someone wants to do it (not part of this lib)
3. Support all queries

**Comment by hamiltop** [comment]
I am pretty confident in the current implementation of the Connection driver. It performs well and has been very robust.

Supervision works fine (unless someone has experience to the contrary).

I would like someone to try to use poolboy to do connection pooling. I don't want to incorporate that into this lib directly, but if there is anything that prevents poolboy from working I'd like to know before we commit to a 1.0.0

We don't currently support STOP and NOREPLY_WAIT. Those should be added.

**Comment by Linicks** [comment]
Is it possible to connect to multiple hosts in a cluster to enhance reliability and performance?

**Comment by hamiltop** [comment]
I'm going to say that's outside the scope of this library. Performance on the database should be fairly agnostic to the number of connections if I understand rethinkdb properly. Performance on the client will be a bit better with a connection pool when large queries are run (reading from the socket is the bottleneck, so a deep queue of data will affect performance for all queries).

In any case, reliability is always a good thing. 

Rather than build our own connection pooling, I'd like to use poolboy. The goal is for the existing `Exrethinkdb.Connection` is to work out of the box with poolboy and to document how to use it with poolboy.

I asked some questions on https://github.com/rethinkdb/rethinkdb/issues/281 (longstanding thread about connection pooling) about the benefits of connection pooling. Hopefully, we get some good insight from them.

I reference to your other thread, documenting how to build a connection pool with poolboy would be fantastic. (And I'm happy to help figuring it all out).

**Comment by jeregrine** [comment]
Once you have it working with poolboy it might make sense to just use it as a default. Most people will need it and better than everyone copying a guide. Or worse not pooling and blaming the library for bad perf.

**Comment by hamiltop** [comment]
Looking at other drivers, https://github.com/ericmj/postgrex, https://github.com/xerions/mariaex and others don't do poolboy.

That said, you do have a point. Perhaps including the code for poolboy and making poolboy and optional dependency is the route to go.

Additionally, connection pooling will require an interesting approach. Anything cursor based (like change feeds) is connection local, but I think we can maintain connection affinity fairly easily. I'll open an issue specifically for connection pool support and lay out a basic approach.

**Comment by jeregrine** [comment]
Yea. I considered that too, but you are also laying out a query api as well. If people use this they most likely wont need a second layer on top like Ecto. 




This lies somewhere between a sql connection and ecto.  I mean i could see this being an adapter for ecto too. Something to consider.

**Comment by hamiltop** [comment]
In writing up https://github.com/hamiltop/exrethinkdb/issues/32 , I convinced myself that poolboy is not the right decision and that we should do our own connection pooling.

**Comment by joshnuss** [comment]
What do you think about making the Connection a named server?
i.e. running a query would require passing the server name to `run/1` (and default server name to `:rethinkdb` when only using one connection).

e.g:

```elixir
# in app supervisor
worker(RethinkDB.Connection, [[db: :sales], [name: :salesdb]]),
worker(RethinkDB.Connection, [[db: :inventory], [name: :inventorydb]])

# running query
table("orders") |> run(:salesdb)
table("products") |> run(:inventorydb)
```
And it would be simple when using just one db:

```elixir
worker(RethinkDB.Connection, []) # dbname will default to rethinkdb

# call run/0, default db name will be `:rethinkdb`
table("products") |> run
```

This would also make it easy to run a query on a remote server, because we can boot a connection on a remote server and call `query |> run(:"foo@computer-name")`

**Comment by hamiltop** [comment]
I think this is already supported.

RethinkDB.run/2 takes the query and a pid or named process.

**Comment by joshnuss** [comment]
@hamiltop oh cool! (thx, did not realize)

**Comment by hamiltop** [comment]
I'm going to close this. I'm pretty happy with Connection as is. Connection Pooling is separate.
