### ISSUE TITLE
insert in a for_each causes argument error

### ISSUE THREAD

**Issue by Lida** [hamiltop/rethinkdb-elixir#100]
```
iex(4)> table("users") |> for_each(fn(obj) -> table("users2").insert(obj) end) |> Repo.run
** (ArgumentError) argument error
                :erlang.apply(%RethinkDB.Q{query: [15, ["pools"]]}, :insert, [%RethinkDB.Q{query: [10, [#Reference<0.0.1.4118>]]}])
       (stdlib) erl_eval.erl:667: :erl_eval.do_apply/6
    (rethinkdb) lib/rethinkdb/query.ex:1865: RethinkDB.Query.func/1
    (rethinkdb) lib/rethinkdb/query.ex:242: RethinkDB.Query.for_each/2
```
Got this error when I was playing around with for_each. The same kind of query works in javascript.

`r.db('test').table('users').forEach(function(user) { return r.db('test').table('users2').insert(user)})`

**Comment by hamiltop** [comment]
`table("users2").insert(obj)` is not valid Elixir. Did you mean `table("users2") |> insert(obj)`?

**Comment by Lida** [comment]
Ah, forgot to convert that into the right syntax.
