### ISSUE TITLE
is rethinkdb-elixir production ready?

### ISSUE THREAD

**Issue by ashwinreddymekala** [hamiltop/rethinkdb-elixir#102]
can we use rethinkdb-elixir in production? when can we expect rethinkdb-elixir 1.0 release?

**Comment by AdamBrodzinski** [comment]
@ashwinreddymekala FWIW i've been using it in production in two apps with great results 👍

**Comment by ashwinreddymekala** [comment]
@AdamBrodzinski It's good to hear that you are using in production with great results.
as README says **The goal for 1.0.0 is to be stable.** is version 0.4.0 unstable?

**Comment by sikanhe** [comment]
@ashwinreddymekala it is stable, its waiting for its last API change from its current response structure to :ok and :error tuple

**Comment by ashwinreddymekala** [comment]
Thanks for all your responses guys I don't see any reason to still open this issue.
