### ISSUE TITLE
distinct does not return all the keys inside an index

### ISSUE THREAD

**Issue by ptgamr** [hamiltop/rethinkdb-elixir#103]
Hi! I come up with one problem and does not know how to fix, maybe someone could point me a direction

Create an index with: 
```
Query.index_create("homeId", Lambda.lambda fn(row) -> row["home"]["id"] end)
```

After that query all the key in the index with
```
Query.distinct(index: "homeId")
# return first 9 keys
```

However, the result doesn't give me all the keys in the index. When I query in RethinkDB Data Explorer, I'm able to retrieve all the keys:
```
r.db('db').table('table').distinct({index: "homeId"})
# return all 16 keys
```

There are ~130k records inside the table, and I don't think the 100k records limit applied here.
Or is there any other way that we can retrieve distinct keys across the table rather than using index?

**Comment by hamiltop** [comment]
Alright. I was able to repro.

It returns a `%RethinkDB.Feed{}`. This means there's more data available. If you call `RethinkDB.Connection.next` on it it will fetch the next batch. Alternatively, you can call `Enum.to_list/1` and it will fetch all the results. (`%RethinkDB.Feed{}` implements `Enumerable`)
