### ISSUE TITLE
Inserting non utf-8 binaries

### ISSUE THREAD

**Issue by brucepom** [hamiltop/rethinkdb-elixir#105]
Hi there. Thanks for the great library. Looking at the source there appears to be support and tests for binaries but I'm getting an error and not sure what I'm doing wrong. I'm new to Elixir and really appreciate any guidance. I'm trying to insert a binary like this:
```
db("my_db") 
|> table("my_table") 
|> insert(%{test: <<245>>}) 
|> MyProject.Database.run
```
And get the following error:
```
(Poison.EncodeError) unable to encode value: <<245>>
```
Running the same procedure but replacing `<<245>>` with `<<1>>` succeeds, presumably because `<<1>>` is a valid string.

Thanks in advance for any suggestions.

**Comment by hamiltop** [comment]
Wrap it in https://hexdocs.pm/rethinkdb/RethinkDB.Query.html#binary/1

**Comment by brucepom** [comment]
Thanks for the quick response! I'm not sure if I'm wrapping the correct thing but I still seem to get the same error message. When you have a moment could you please check out the code below and let me know if this is what you mean?
```
binary_data = RethinkDB.Query.binary(<<245>>)
db("my_db") 
|> table("my_table") 
|> insert(%{test: binary_data}) 
|> MyProject.Database.run
```

Thanks again.

**Comment by hamiltop** [comment]
Yeah. That's the correct way to do it. This is a bug. I'll take a look and
try to sort it out.

**Comment by hamiltop** [comment]
I just tried to reproduce and couldn't, so I'm happy to hear you figured it out. Thanks!
