### ISSUE TITLE
Geo Query Example Help

### ISSUE THREAD

**Issue by Linicks** [hamiltop/rethinkdb-elixir#108]
All,
  I'm trying to use rethinkdb-elixir to implement the geo locations examples found in the docs http://www.rethinkdb.com/docs/geo-support/python/.  It's been awhile since I've played with Elixir and this driver, so I'm a little rusty on how to get things done.   I've tried several iterations, but this is the latest version of the RQL query that I'm trying to perform: 

    def get_neighboring_locations do

        # Origional Query
        # var point = r.point(-122.422876,37.777128); 
        # r.db('geo_test').table('geo').getNearest(point, {index: 'location', maxDist: 500, unit: 'mi'})
       
        point = reql_geo_point(-122.422876,37.777128)
          
        q = table("geo")
           |> get_nearest(point, index: 'location', max_dist: 500, unit: 'mi')
           |> Elxrdb.Connection.run

        results = inspect(q.data)
        IO.puts "#{results}"
    end

Thanks!
--Nick

**Comment by hamiltop** [comment]
It looks right. What error are you seeing?

**Comment by Linicks** [comment]
Hi Peter,
  I'm getting the following compilation error:

>== Compilation error on file lib/geotst.ex ==
** (CompileError) lib/geotst.ex:44: undefined function reql_geo_point/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

Here are my system stats:

>$iex
>Erlang/OTP 19 [erts-8.0.2] [source-9503fff] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]
Interactive Elixir (1.3.2) - press Ctrl+C to exit (type h() ENTER for help)

Thanks!
--Nick

**Comment by hamiltop** [comment]
Well.... `undefined function reql_geo_point/2`

that's the problem. that's a type spec, not a function. It's defined here: https://hexdocs.pm/rethinkdb/RethinkDB.Query.html#t:reql_geo_point/0

just use a tuple. `point = {-122.422876,37.777128}`

**Comment by Linicks** [comment]
Peter,
  I replaced the point with a tuple, and I'm compiling just fine now!  I'm  unfortunately getting another error:

>iex(3)> Geotst.get_neighboring_locations
%{"b" => ["unit"], "r" => ["Second element in a Term is neither arguments nor optional arguments."], "t" => 17}
:ok

--Nick

**Comment by hamiltop** [comment]
Alright. that's a bug. I'll take a look when I get a chance.

**Comment by Linicks** [comment]
Hi Peter,
  I know you've been working hard on this driver, and have been busy with other obligations.  I created a small bounty on this bug so that you can get a  cup of coffee, or whatever it is that you like when you have a chance to fix it.  Here is a link to the bounty:

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=36746249)](https://www.bountysource.com/issues/36746249-geo-query-example-help?utm_source=36746249&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Thanks!
--Nick

**Comment by hamiltop** [comment]
What a kind gesture! I'm a little ashamed to say it completely got my attention.

This is the corrected query:
```
table("geo") |> get_nearest(point({-122.422876,37.777128}), index: "location", max_dist: 500, unit: "mi")
```

In case you missed it:

```
iex(19)> Poison.encode!("location")
"\"location\""
iex(20)> Poison.encode!('location')
"[108,111,99,97,116,105,111,110]"
```

This is a really rough one. I don't know the right way to deal with this. This isn't the first time someone has gotten burned by it and it won't be the last.

**Comment by sikanhe** [comment]
@Linicks unlike javascript, quotes and single quotes means different things in Elixir. Double quotes means string (which is what you want here) and single quote means a character list.

**Comment by Linicks** [comment]
Hey All,
  The query is working for me now.  Many thanks!!
--Nick

**Comment by hamiltop** [comment]
Are we ok closing this issue?

**Comment by Linicks** [comment]
Hi Peter,
  My query is working just fine now, so we should probably get this one off the books.  I appreciate the help from you and sikanhe.  Don't forget to claim your bounty :)

--Nick
