### ISSUE TITLE
How to set user/password for connection?

### ISSUE THREAD

**Issue by vorce** [hamiltop/rethinkdb-elixir#113]
I am unable to figure out how to set the user and password to use to connect to rethinkdb. Is this supported? How?

Any pointers would be appreciated.

**Comment by vorce** [comment]
I think I can answer this myself now. Please correct me if I'm wrong here.

At the moment this is not supported. User+password auth was introduced in rethinkdb protocol `V1_0 `. Before that (`V0_3 and V0_4`) something called an authentication key was instead used it seems.
I got this from the excellent [rethinkdb docs on writing drivers](https://www.rethinkdb.com/docs/writing-drivers/).

Here's a key part that solved my problem:
_When communicating with RethinkDB 2.3 or later, the authentication key will be compared to the admin user account password._

Ideally `rethinkdb-elixir` would support the new handshake protocol with user/password. I might give it a go myself. :)

**Comment by hamiltop** [comment]
Please give it a go. I'm more than happy to help. Also, look at https://github.com/almightycouch/rethinkdb-elixir/blob/3fe4116bb8abd5402410e2ac69281780935b2d67/lib/rethinkdb/connection/multiplexer.ex#L119 . That PR was closed but the work was done to get the auth stuff and could probably get pulled in fairly easily.
