### ISSUE TITLE
Use Protocol Buffers

### ISSUE THREAD

**Issue by jeroenvisser101** [hamiltop/rethinkdb-elixir#114]
https://rethinkdb.com/docs/writing-drivers/

https://github.com/rethinkdb/rethinkdb/blob/next/src/rdb_protocol/ql2.proto

What's the stand on moving from the HTTP/JSON API to the ProtoBuf API?

**Comment by hamiltop** [comment]
Client drivers are supposed to be HTTP/JSON. That's the latest I've heard from the RethinkDB team.

**Comment by jeroenvisser101** [comment]
Oh really? I could be wrong, but I think they're using Protocol Buffers now. Let me ask them tonight on Google Groups.

**Comment by hamiltop** [comment]
The drivers originally used Protobuf, but then switched to JSON with 2.0.

https://rethinkdb.com/docs/writing-drivers/ outlines how to create a JSON driver, if you look at the examples.

https://github.com/rethinkdb/rethinkdb/blob/next/src/rdb_protocol/ql2.proto is meant to be used as a reference/generatorfor opcodes and function signatures.

**Comment by jeroenvisser101** [comment]
Ah right, I thought they moved to Protobuf for performance, I guess it's alright then :)
