### ISSUE TITLE
Map types merge instead of update

### ISSUE THREAD

**Issue by ijcd** [hamiltop/rethinkdb-elixir#115]
I'm working on the integration tests for rethinkdb_ecto and this test is failing:

```
  @tag :map_type
  test "map type on update" do
    post = TestRepo.insert!(%Post{meta: %{"world" => "hello"}})
    assert TestRepo.get!(Post, post.id).meta == %{"world" => "hello"}

    post = TestRepo.update!(Ecto.Changeset.change post, meta: %{hello: "world"})
    assert TestRepo.get!(Post, post.id).meta == %{"hello" => "world"}

    query = from(p in Post, where: p.id == ^post.id)
    TestRepo.update_all(query, set: [meta: %{world: "hello"}])
    assert TestRepo.get!(Post, post.id).meta == %{"world" => "hello"}
  end
```

The middle assertion is failing, because it looks like a merge is happening instead of an update. It seems that Ecto believes this should be a merge. Is this specified differently in rethinkdb-elixir  or is this just not tested or underspecified?

```
  1) test map type on update (Ecto.Integration.TypeTest)
     deps/ecto/integration_test/cases/type.exs:163
     Assertion with == failed
     code: TestRepo.get!(Post, post.id()).meta() == %{"hello" => "world"}
     lhs:  %{"hello" => "world", "world" => "hello"}
     rhs:  %{"hello" => "world"}
     stacktrace:
       deps/ecto/integration_test/cases/type.exs:170: (test)
```

**Comment by hamiltop** [comment]
I think this is a bug for the rethinkdb_ecto project.

**Comment by ijcd** [comment]
As near as I can tell the update query is passed correctly directly to the
connection, which seems to be a rethinkdb connection. Are you saying
rethinkdb_ecto should try to emulate the correct behavior?

**Comment by hamiltop** [comment]
I'm saying that as it stands there are two possibilities:

1) There's a bug in the implementation of ReQL `update`. (It should mirror the ruby spec: https://www.rethinkdb.com/api/ruby/#update)
2) There's a bug in how `RethinkDB.Ecto` is using ReQL.

I know of no such bug in ReQL update. If you can find such a bug, I'd be happy to help you fix it. So that leaves the second case. Perhaps `RethinkDB.Ecto.update` should use `replace` instead. https://hexdocs.pm/rethinkdb/RethinkDB.Query.html#replace/2

**Comment by ijcd** [comment]
I'm having a hard time parsing what the intended behavior is *supposed* to be. Replace seems to be for whole documents (this is grafting a change onto a nested value... which has a lot of variants that could be acceptable with regard to replace, merge, etc).

Indeed, if I use replace() here, nothing happens. There is no change in the document.

I'm wondering if the test is even correct (though this is in Ecto...) https://hexdocs.pm/ecto/Ecto.Changeset.html#change/2

```
When a changeset is passed as the first argument, the changes passed as the second argument are merged over the changes already in the changeset if they differ from the values in the struct. If changes is an empty map, this function is a no-op.
```

That seems to indicate that a merge is the expected behavior. I'm not sure where to go with this... I can't tell where the issue is. :(

Though I do notice that mongodb_ecto does incorporate this test, so they at least accept the Ecto acceptance test.

**Comment by ijcd** [comment]
Looking at mongodb_ecto, it seems to do about the same amount of work as rethinkdb_ecto is in the update method -- mostly just passing this down to the driver. I wonder if this is related to how rethinkdb handles nested docs (https://www.rethinkdb.com/api/ruby/update/)

> Example: Replace all of Bob’s IM records. Normally, update will merge nested documents together; to replace the entire "im" document, use the literal command.
> 
> ```
> r.table('users').get(10001).update(
>     {:contact => {:im => r.literal({:aim => "themoosemeister"})}}
> ).run(conn)
> ```

If this is the case, how and at what level do you think this should be handled?

**Comment by hamiltop** [comment]
I think you have the correct information. This is one of the reasons I'm not terribly fond of Ecto for RethinkDB. It just provides a layer for impedence mismatch. ReQL already has semantics for querying and updating and Ecto in this case is causing confusion around update semantics.

**Comment by ijcd** [comment]
Indeed. Closing.
