### ISSUE TITLE
Filter by custom condition / regex

### ISSUE THREAD

**Issue by KirillTemnov** [hamiltop/rethinkdb-elixir#122]
I was looking for a query, that `filter` result by regex but couldn't find any working example.

Here's my sample:
We have a customers  and want to review all who has email on GMail. 

```
Query.table("customers")  
|> Query.filter(fn (doc) -> 
       doc[:email] 
       |> String.ends_with?("gmail.com") 
    end) 
|> RethinkDB.run
```

Error:
```
function RethinkDB.Q.fetch/2 is undefined (RethinkDB.Q does not implement the Access behaviour)
```

Can someone explain me how to use `filter` and `fn` together?

**Comment by hamiltop** [comment]
Add a `lambda` to your filter function in order to use `[:email]`

**Comment by KirillTemnov** [comment]
Can you explain more explisit?

I've already tried lamdas.

This code:

```
Query.table("customers")  
|> Query.filter(lambda fn (doc) -> 
       doc[:email] 
       |> String.ends_with?("gmail.com") 
    end) 
|> RethinkDB.run
```

Gives error

```
(CompileError) iex:21: undefined function lambda/1
```

Here's another attemp:
```
Query.table("customers")  
|> Query.filter( &(&1[:email] |> String.ends_with?("gmail.com") ) )
|> RethinkDB.run
```

With error

```
(UndefinedFunctionError) function RethinkDB.Q.fetch/2 is undefined (RethinkDB.Q does not implement the Access behaviour)
```

**Comment by hamiltop** [comment]
You need to `require Lambda` or `import Lambda` beofre using it.

https://github.com/hamiltop/rethinkdb-elixir#filter
https://hexdocs.pm/rethinkdb/RethinkDB.Lambda.html

**Comment by KirillTemnov** [comment]
That's worked, thanks!
