### ISSUE TITLE
Renew SSL Certificate for Testing

### ISSUE THREAD

**Issue by optikfluffel** [hamiltop/rethinkdb-elixir#127]
- [ ] Renew `test/cert/host.crt`

Because it's invalid since `Jan 22 21:41:53 2017 GMT` and currently causes the SSL tests to fail.
See #126  for example.

**Comment by russmatney** [comment]
@hamiltop Is this as easy as generating new certificates? I can take a shot at it tonight.

**Comment by hamiltop** [comment]
Yeah, should be pretty easy.
