### ISSUE TITLE
Upgrade Poison

### ISSUE THREAD

**Issue by gogocurtis** [hamiltop/rethinkdb-elixir#137]
Poison 3.1 is out.. is there any reason to have the version pinned at 1.5 or 2?

**Comment by rschooley** [comment]
This causes an issue when getting deps:

```
Running dependency resolution...

Failed to use "poison" because
  ecto (version 2.1.6) requires ~> 2.2 or ~> 3.0
  rethinkdb (version 0.4.0) requires ~> 1.5 or ~> 2.0
  mix.lock specifies 3.1.0
```

I will open a PR updating these instead of mucking around with old allowing versions of dependencies in my project.

**Comment by edwinallenz** [comment]
@gogocurtis  do you have any issues updating Posion, I'm facing the same problem

**Comment by gogocurtis** [comment]
@edwinallenz I switched to Poison 2.0 as there was nothing specific about 3.1 that I needed - I mostly wanted to try out this driver and try the query lang and see how fast I could load the db.

the patch @rschooley Rschooley put in for a pull request should solve the issue, one could use his github branch as the package location via :github key in mix deps or @hamiltop may have other thoughts.

**Comment by edwinallenz** [comment]
thanks update

**Comment by gogocurtis** [comment]
<3

**Comment by edwinallenz** [comment]
@hamiltop it's posible to tag this merge?
