### ISSUE TITLE
Math and Logic Queries

### ISSUE THREAD

**Issue by hamiltop** [hamiltop/rethinkdb-elixir#24]
```
+
-
*
/
mod
&&, and
||, or
eq
ne
>, gt
>=, ge
<, lt
<=, le
not
random
```

Most of these have been written. It is important that both the verbose an the symbol are implemented (eg `add` and `+`). The symbol should be defined in `Exrethinkdb.Lambda.lambda` and translate to the verbose function.

specs/tests/docs as usual.

Some of these are overridden to do magic things to arrays. The `lambda` implementation should probably not allow something like `[a] + [b]`. Instead it should support `[a] ++ [b]` even though that translates to the same ReQL. Other symbols used in other languages are because they lack the ability to do fancy macro things. So in python `|` is used to mean `||`. We can override `||`. Our only limitation is `%` for `mod`. We can't do that.

**Comment by hamiltop** [comment]
Finished and found a few other limitations.

1. `and`, `or` and `not` are keywords. They can only be declared via unquoting. You can't write a spec for them. You also can't import their module as they conflict with functions in the kernel namespace. The current solution is to name them `and_r`, `or_r`, `not_r`. We can use the originals via macros. 
2. `div` is in the `Kernel` namespace so we had to name it `divide`
3. Many operations take two arguments in their default form. Most of these actually work with N arguments. Right now every op that supports N can be called with a list of arguments. Is this a good idea?

In addition to discussions around the above, I'd love for someone to test all these functions out.

**Comment by nurugger07** [comment]
Seems like we could do something better. The `and` & `or` are caught at the AST level in ecto I believe. I wouldn't mind taking a look at this.

**Comment by hamiltop** [comment]
I'm going to close these tickets. Once the whole query language is implemented, I'm going to review all the closed tickets and transfer comments to a new "second pass" issue where we correct rough edges.
