### ISSUE TITLE
Dates and Times Queries

### ISSUE THREAD

**Issue by hamiltop** [hamiltop/rethinkdb-elixir#25]
now
time
epoch_time
iso8601
in_timezone
timezone
during
date
time_of_day
year
month
day
day_of_week
day_of_year
hours
minutes
seconds
to_iso8601
to_epoch_time

None of this currently exists. There will be pseudotypes as well here.

Normal specs/tests/docs.

**Comment by hamiltop** [comment]
https://github.com/hamiltop/exrethinkdb/issues/24 should support Time pseudotype

**Comment by hamiltop** [comment]
What datetime format should I use here?

Timex or vanilla erlang stuff?

**Comment by nurugger07** [comment]
There is also [Chronos](https://github.com/nurugger07/chronos) which would solve the issues. I'm looking to get involved in this library and can help in this area.

**Comment by hamiltop** [comment]
@nurugger07 Interesting. I like how Chronos only uses erlang dates and times. Timex feels a bit heavy handed. With Chronos we can allow better interoperability with other libs. This is a huge gap in the Elixir ecosystem, with Ecto rolling their own Date structs.

The problem I think everyone is hitting is that they want to use protocols (JSON.encode in our case) with whatever date structure. Traditional erlang tuples sort of fall short in that regard.

**Comment by nurugger07** [comment]
@hamiltop Chronos was intended to be minimal and would be able to JSON encode a datetime without issue. Plus if additions/changes need to be made, we would have that flexibility.

**Comment by hamiltop** [comment]
We have a reql pseudotype:

{
    $reql_type: "TIME",
    epoch_time: <timestamp>,
    timezone: <string>
}

We have the opportunity to convert them when we build the query. We also
have a hook in run where we traverse the query looking for special things
(right now it's just function args). So long as we can safely detect them
any format should work.

**Comment by nurugger07** [comment]
@hamiltop just wanted to update you. I have epoch_time in chronos now and working to implement timezones. They are actually done it's just a matter of getting them all in now. There will also be an ISO8601 format function. I should wrap this up tomorrow and then start on this end.

**Comment by hamiltop** [comment]
Great. I have some rough precedent set for Pseudotypes with `RethinkDB.Pseudotypes.Binary`. I've got a `parse` and a `wrap` for the type. I'm not super committed to what I have so if you think you see a clear path to better code and structure be my guest. Otherwise, just follow my lead. My focus right now is getting all the query language built. We'll likely revisit pseudotypes when we have a feature complete client to start getting feedback on.

**Comment by nurugger07** [comment]
Sounds good.

**Comment by joshnuss** [comment]
Here's a list of the op codes needed:

- now

  `now` = `[103, []]`

- time

  `time(year, month, day, "Z")` = `[136, [year, month, day, "Z"]]`
  `time(year, month, day, hour, minute, seconds, "Z")` = `[136, [year, month, day, hour, minute, seconds, "Z"]]`

- epoch_time
  
  `epoch_time(n)` = `[101, [n]]`
  
- iso8601
  
  `iso8601("1986-11-03T08:30:00-07:00")` = `[99, ["1986-11-03T08:30:00-07:00"]]`

- in_timezone

  `xyz |> in_timezone(offset)` = `[104, [ xyz, offset]]`

- timezone

  `xyz |> timezone` = `[127, [xyz]]`

- during

  
- date
  
  `xyz |> date` = `[106, xyz]`

- time_of_day

  `xyz |> time_of_day` = `[126, xyz]`

- year
  
  `xyz |> year` = `[128, xyz]`

- month
  
  `xyz |> year` = `[129, xyz]`

- day

  `xyz |> year` = `[129, xyz]`

- day_of_week

  `xyz |> year` = `[130, xyz]`

- day_of_year

  `xyz |> year` = `[131, xyz]`

- hours

  `xyz |> hours` = `[133, xyz]`

- minutes

  `xyz |> minutes` = `[134, xyz]`

- seconds

  `xyz |> seconds` = `[135, xyz]`

- to_iso8601

  `xyz |> to_iso8601` = `[100, xyz]`

- to_epoch_time

  `xyz |> to_epoch_time` = `[102, xyz]`

**Comment by hamiltop** [comment]
The opcodes, tests, and docs are faily straightforward. What isn't straighforward is how to deal with The Psuedotype of time. It looks like under the hood it consists of a unixtime plus a timezone.

I'm going to implement it in terms of just those two values. We can strap on Chronos or Timex or whatever later.

**Comment by hamiltop** [comment]
All functions present in master now.
