### ISSUE TITLE
Control Structures Queries

### ISSUE THREAD

**Issue by hamiltop** [hamiltop/rethinkdb-elixir#26]
args
binary
do
branch
for_each
error
default
expr
js
coerce_to
type_of
info
json
http
uuid

These are all new, except for `branch` which has an early implementation along with a lambda mapping. Other functions might also need a lambda mapping.

`expr` might be internal only, since we are going to allow native elixir data types everywhere.

Usual specs/tests/docs

**Comment by hamiltop** [comment]
`do` is a keyword. Additionally, the spec says it accepts `FUNCTION(*), DATUM...` Which is pretty hard to handle in Elixir. The current implementation is to take one data arg and one function. I think we should push weird stuff to the user by requiring them to use `args`.

**Comment by hamiltop** [comment]
`expr` not necessary since we have a prefix driver (`expr` basically just wraps an existing data object so it can be used as an `infix` driver)

**Comment by hamiltop** [comment]
Finished and pushed.

Most of the functions here are weird. I would like to eliminate their direct usage as much has possible. Anytime they are used, I think we have an opportunity to make this driver better suited for Elixir.

**Comment by ptgamr** [comment]
How could you convert such query to Elixir code?

```
r.branch(r.table("users").getAll(email, {index: "email"}).isEmpty(),
         r.table("users").insert(user),
         {})
```
