### ISSUE TITLE
Supervison and connection pooling

### ISSUE THREAD

**Issue by mossplix** [hamiltop/rethinkdb-elixir#3]
Hey @hamiltop I think the genserver should be supervised and also should have some sort of connection pooling . I am going to do a pull request later with this :)

**Comment by hamiltop** [comment]
That was the plan. Thanks for volunteering!

**Comment by hamiltop** [comment]
I just did a refactor of connections. Now a connection is just a pid and therefore supports supervision. It also registers by default.

**Comment by hamiltop** [comment]
@mossplix If you still want to help out, I've opened https://github.com/hamiltop/exrethinkdb/issues/10 as sort of an epic about what needs to be done with connections.

Supervision works well (AFAICT) but I'd love feedback on it.

What I would really like help with is for someone to try to use poolboy and exrethinkdb together. I think that's a better route than trying to build connection pooling directly into exrethinkdb.

**Comment by mossplix** [comment]
Sure thing ..  I have been looking into it  . I like the way pooler was added to the riak adaptor (https://github.com/drewkerrigan/riak-elixir-client), where both worlds are supported .

**Comment by hamiltop** [comment]
This is captured in https://github.com/hamiltop/rethinkdb-elixir/issues/32
