### ISSUE TITLE
Some Fully Functional Examples

### ISSUE THREAD

**Issue by Linicks** [hamiltop/rethinkdb-elixir#31]
@hamiltop 
I've been trying to get up to speed with ExrethinkDB for a couple of days, and have only had some success.  As someone that's learning Elixir, it gets frustrating when you have to read the source, read the docs, and stumble through the basics.  This isn't necessarily a bad thing, but slows the process considerably.   Some fully functional examples would go a long way to help those new to Elixir, get up to speed in a more reasonable time.  The little snippets just aren't enough.  I was able to get the following code to work, but I still haven't been able use the query results effectively, etc.  

############################

#Define an Example Elixir Module.
defmodule EXMPL1 do
  #Creat an alias to tidy up the use of the API.
   alias Exrethinkdb.Query

     #Get users from the "exampledb" database.
     def getusers do

      #Connect to the database.
      conn = Exrethinkdb.connect([host: "10.0.0.1", port: 28015])

      #Query the database as get a specified user.
      q = Query.db("exampledb")
        |> Query.table("users")
        |> Query.filter(%{name: "Peter"})
        |> Exrethinkdb.run conn

      #Print the query result to standard out.
      IO.puts "#{inspect(q)} is a list"

    end
end

############################

This prints the following Example data to Standard out:

%Exrethinkdb.Collection{data: [%{"age" => 30, "id" => "381c7090-d8a1-4301-bf2d-63235a521fe3", "name" => "Peter", "userId" => "f62255a8259f"}]} 

This is great, but I'm stuck trying to get a specific part of the result like the users name.  Ultimately it would be great to have a developers guide like this:
  - http://www.rethinkdb.com/docs/guide/javascript/
I'm for course happy to work on that, but I need a little more hand holding at the moment, and I'm sure others do as well. 

Many, Many Thanks!
-- Nick

**Comment by hamiltop** [comment]
I'm delighted to have you help. Hand holding is not a problem at all. In fact, it may be the easiest path to good documentation.

One problem you're having is that the code is in the middle of a big rewrite. Also, I have yet to publish the docs.

Here's my proposal:

1. You come up with a handful of scenarios and I'll help you walk through them. I'll make sure idiomatic usage of 
2. For each scenario we go through, you document how to use it. Focus on others new to both Elixir and rethinkdb.

We'll either put this in the repo on in the github wiki (or put together a github page for it all).

**Comment by Linicks** [comment]
That sounds great!  I will start working on the wiki for now just to make it easier to build up the docs, then we can move them into something more formal down the road if desired.  A github page would add allot of professionalism to the project, and should be on the radar once things have been firmed up.

**Comment by hamiltop** [comment]
Looking through the wiki (thanks for all the effort!) I wanted to chime in with a point or two.

* "pipeline enabled" - I meant that in the network connection sense. This driver, unlike the official rethinkdb drivers, takes advantage of connection pipelining, where multiple requests can be sent across the same connection and will be processed in parallel. It's an implementation detail but a pretty cool one.
* Many things being named are not currently implemented. For example, connect doesn't currently accept a default database. It should. Please open issues whenever you encounter a problem with the behavior you are describing.

Thanks for putting in the effort and time. It is very appreciated!

**Comment by hamiltop** [comment]
@Linicks Just saw a comment you made on IRC about some confusion with results that are a list.

`Collection` implements enumerable so instead of doing `Enum.map(result.data, ...)` you could just do `Enum.map(result, ...)`

In your particular case, `Enum.at(result, 0).fname` might have been a better choice.

So, with the correct approach presented, what was confusing to you? Were you expecting rethinkdb to return only a single result from `filter`? Or was it hard to see that the data was a list when you inspected it?

This is good feedback and I really appreciate your help in knocking off rough edges.

**Comment by Linicks** [comment]
@hamiltop ,

* "pipeline enabled" - I meant that in the network connection sense. This driver, unlike the official rethinkdb drivers, takes advantage of connection pipelining, where multiple requests can be sent across the same connection and will be processed in parallel. It's an implementation detail but a pretty cool one.

  Thanks for the clarification! I updated the wiki so that it reflects this clarification.

* Many things being named are not currently implemented. For example, connect doesn't currently accept a default database. It should. Please open issues whenever you encounter a problem with the behavior you are describing.

  Getting all of the the I's dotted and T's crossed will take some time for sure.  The guide is based on the basics operations that you need to use RethinkDB, so hopefully we can get those in place.  I will start adding issues as I work though the details.

*So, with the correct approach presented, what was confusing to you? Were you expecting rethinkdb to return only a single result from filter? Or was it hard to see that the data was a list when you inspected it?  

  The big thing to keep in mind is that the learning curve is fairly high for developers that are new to Elixir, functional programming, and the implementation details of the driver itself.  I have been developing on and off for many years which is good and bad.  Because I'm used to other tools, and a non functional coding styles, I naturally make "assumptions" about how things should work, and not necessarily how they do.  For example, I was able to figure out how to perform a few basics by working with the snippets in the read-me, looking through the code,  and  the tests.  One of the things that was tripping me up was that I was expecting a map of the record so that I could access each of the data members individually.   In my mind I wanted to do something like this:
```
        ...
        #Query the database and get a specified user.
        q = Query.db("exampledb")
          |> Query.table("users")
          |> Query.filter(%{fname: "Arnold"})
          |> RethinkDB.run conn

        #Print the query result to standard out.
        IO.puts "------------------------------------------------------"
        IO.puts " The users name is:  #{q.data.fname, q.data.lname}"
        IO.puts "------------------------------------------------------"

    end
```

* And get a result of : **The users name is: Arnold Schwarzenegger**

I was able to piece together this query, and didn't get the exact functionality I was looking for, but did get closer:

```
  ...
  #Query the database and get a specified user.
      q = Query.db("exampledb")
        |> Query.table("users")
        |> Query.filter(%{fname: "Arnold"})
        |> map(lambda fn (person) ->
           person[:fname] + " " + person[:lname] end)
        |> RethinkDB.run conn

      #Print the query result to standard out.
      IO.puts "------------------------------------------------------"
      IO.puts "Is the query result q a map?: #{is_map(q)} "
      IO.puts "Query results for the map q: #{inspect(q)} "
      IO.puts "------------------------------------------------------"
      IO.puts "Is the query result q.data a list?: #{is_list(q.data)} "
      IO.puts "Query results for the list q.data: #{inspect(q.data)} "
      IO.puts "------------------------------------------------------"
```
* I get a result of : 
```
------------------------------------------------------
Is the query result q a map?: true 
Query results for the map q: %RethinkDB.Collection{data: ["Arnold Schwarzenegger"]} 
------------------------------------------------------
Is the query result q.data a list?: true 
Query results for the list q.data: ["Arnold Schwarzenegger"] 
------------------------------------------------------

```

Hopefully this illustrates some of the rough edges that I've been running into.  I'm having allot of fun learning Elixir, and think it's a natural fit for RethinDB.  As a part two of the jump-start docs, I hope to develop a guide that focuses on Phoenix framework integration. I believe that most users will want to use this driver with Phoenix, and will want it to be "Rails" easy to get started with.  

-- Nick

**Comment by hamiltop** [comment]
So that's less a function of this driver and Elixir as it is RethinkDB itself. `filter` returns multiple results. Look at the python driver for example: http://rethinkdb.com/api/python/#filter

Play around with the data explorer when working out a query. It's pretty handy.

**Comment by Linicks** [comment]
* So that's less a function of this driver and Elixir as it is RethinkDB itself. filter returns multiple results.   Look at the python driver for example: http://rethinkdb.com/api/python/#filter

  I think you may have missed the point I was trying to make.  I'll try to be more clear and concise going forward.

* Play around with the data explorer when working out a query. It's pretty handy.
  
  Definitely, I've been using it for quite some time.

**Comment by hamiltop** [comment]
@Linicks You said:

     In my mind I wanted to do something like this:

        ...
        #Query the database and get a specified user.
        q = Query.db("exampledb")
          |> Query.table("users")
          |> Query.filter(%{fname: "Arnold"})
          |> RethinkDB.run conn

        #Print the query result to standard out.
        IO.puts "------------------------------------------------------"
        IO.puts " The users name is:  #{q.data.fname, q.data.lname}"
        IO.puts "------------------------------------------------------"

    end
    And get a result of : The users name is: Arnold Schwarzenegger

My point was that q would never be a single records, due to how rethinkdb treats `filter`. It will always return a list of records. The would have been the case in any language.

Anyway, glad you figured it out.

**Comment by hamiltop** [comment]
I think we got a decent start at a wiki. Closing.
