### ISSUE TITLE
Supervised Changefeeds

### ISSUE THREAD

**Issue by hamiltop** [hamiltop/rethinkdb-elixir#37]
For changefeeds to be useful in a production system they should be reliable (and therefore supervised).

High level design:

A changefeed is a Supervised GenEvent. A default handler is started with `handle_info` set up to handle the following situations:

1. Connection dies. The Connection will be monitored so we should receive a `DOWN` message. This should be handled by creating a new changefeed on a new connection and resuming operation.
2. Initial setup. We should not block in the supervisor so we should start the GenEvent and then send a message to kick off the connection in the GenEvent process.

ChangeFeeds can be started in the main application supervisor or alternatively a `:simple_one_for_one` supervisor could be created and ChangeFeeds can be created at runtime. The design should work for both cases.

One complication will be procuring a connection. If a connection dies, a ChangeFeed should not die. Rather, it should try to find a new connection. With named connections this is easy enough, as well as with a named connection pool. Unnamed connections will need some mechanism for procuring a new connection or perhaps we just let those ChangeFeeds die.

Client interaction would be via installing handlers for events. This could be a simple `GenEvent.stream` or it could be an actual handler.

It would be useful to provide an example of using this with Phoenix Channels.

**Comment by ericmj** [comment]
I don't think changefeeds should be GenEvents, a changefeed can just be a process that sends messages to other registered processes or can be used as a stream. What's the reasoning for making it a GenEvent?

The changefeed should either die or at least inform all its users when the connection dies so that they know they are losing messages.

**Comment by hamiltop** [comment]
"a process that sends messages to other registered processes or can be used
as a stream"

I feel like building this on top of a vanilla GenServer is going to result
in something similar to GenEvent.

The argument against that would be that it would be a GenEvent with many
near-identical handlers (one per subscribing process) or exactly one
handler (that keeps track of all subscribing processes). If the two
approaches are functionally equivalent then exactly one handler is better
for performance reasons. And exactly one handler turns a GenEvent into a
less flexible GenServer, so we might as well start with a GenServer.

So to me, the question is around how many types of handlers will there be?
I don't want to expose the GenEvent for users to attach anything they want
(the fact that handler code runs on the GenEvent has always made me super
nervous about making them too accessible. One long running handler sort of
breaks the whole thing.).

One handler will be "forward messages to me". This will be the use case for
Phoenix Channels. The channel gets a message and deals with it in
handle_info. This will most likely be asynchronous, which limits
backpressure control.

Another handler will be a streaming handler. This can be done just like we
current do Enumerable for cursors. The process requests data and blocks
until it receives a bit. Backpressure built in. This could be done via
Streams for GenEvent or via handle_call on a GenServer (we do this for
requests in Connection).

Any other handlers needed? If it is indeed just those two cases then we do
have somewhat of an isomorphism between using a GenEvent and a GenServer.
Using a GenServer would prove simpler.

**Comment by ericmj** [comment]
You don't have to implement the streaming handler, elixir does it for you with `GenEvent.stream`.

**Comment by hamiltop** [comment]
Yes. I was counting that as the streaming handler with GenEvent (though if you used a GenServer you would need to implement it).

Your original comment suggested not to use GenEvent (and therefore GenEvent.stream). How would you have recommended streaming without GenEvent?

**Comment by ericmj** [comment]
It's a bit tricky if you want to protect against overload. One issue is that with sending messages from the changefeed (or even when sending messages between the connection and the changefeed if they are different processes) is that you may be sending messages faster then you can consume them. That can lead to what is essentially a memory leak.

If the changefeed and connection was the same process it would be easy to solve, poll for messages from the receiving and only accept more tcp data if there are no messages to send. Then you have to hope that the server knows how to shed overload messages.

Another way is that the receiving process ACKs every message and the sending process will buffer N messages and if the buffer goes over N you start shedding messages. You would need to do this on both the changefeed and connection process.

Sidebar: I see that you run the socket with `active: true`, you probably want to change that to `active :once` to protect against receiving TCP data faster than you can process it.

**Comment by hamiltop** [comment]
https://github.com/hamiltop/rethinkdb-elixir/issues/39 created.

The way that changefeeds work is essentially long polling for changes. This solves backpressure perfectly. I don't plan on changing Connection to allow for pushing data to ChangeFeeds. ChangeFeed is just another client like all others. The value in it being a separate supervised process is that it can be restarted to use a new connection if the current one fails. We would definitely notify clients that the feed is restarting so they can deal with lost messages accordingly (generally either ignore or make a single request for data to fill in the gap).

To return to the original discussion, my proposal was to have one GenEvent per ChangeFeed with multiple client processes consuming events via handlers (including the stream handler). Are you suggesting to not have an extra process and just have the Connection deal with subscribers directly? Or are suggesting a similar structure (1 connection process + 1 changefeed process + N subscribers) and discussing the details of the changefeed process?

**Comment by hamiltop** [comment]
This is in master now. See https://github.com/hamiltop/rethinkdb-elixir/blob/master/lib/rethinkdb/changefeed.ex#L2 for information on how to use.

It needs some people tinkering with it and trying to break it, but I'm comfortable enough with it that the basic API won't change.

We will, however probably see some tweaks around things like errors that we catch vs errors that we allow to crash.

I'm going to close this and open new tickets as bugs are reported.
