### ISSUE TITLE
undefined function: RethinkDB.Query.insert/2 

### ISSUE THREAD

**Issue by tupaja** [hamiltop/rethinkdb-elixir#47]
Hi, I followed instructions from the README to insert a record with RethinkDB.Query module, but it throws: 

```
undefined function: RethinkDB.Query.insert/2
```

After investigating the code I found out, that ```insert``` and a bunch of other functions are being imported with ```__using__```, so the RethinkDB.Query module should be ```use```d not ```alias```ed, correct? But then it won't work with qualified name like ```Query.insert``` like in the README, will it?

Sorry if the question turns out to be a nooby one, I'm still trying to wrap my head around elixir :smile:

**Comment by hamiltop** [comment]
I'm in the middle of changing where these are all defined. My apologies for
the confusion.

For background, my goal was to separate the different parts of the query
language into different modules for maintainability. If you `use RethinkDB
` everything is under one namespace. This has cause more confusion than
good, so I'm going to move everything under the single namespace of
RethinkDB.Query

Thanks for your feedback! Your confusion is completely valid and is a
driving factor in how the functions should be presented. The outdated
README doesn't help either.

**Comment by tupaja** [comment]
Ok, that definitely explains it. Thanks for the response, and keep up the good work :+1:

**Comment by hamiltop** [comment]
Everything has now been moved under `RethinkDB.Query`. The README should be accurate again.
