### ISSUE TITLE
How to specify the database name to which you are connecting?

### ISSUE THREAD

**Issue by jasdeepsingh** [hamiltop/rethinkdb-elixir#49]
Pardon, my question if it's too silly, as I'm new to the Elixir way of things. I looked through the documentation and tests, but could not find something that would hint towards how to specify the target database to connect to?

**Comment by hamiltop** [comment]
Database is a part of the query.

```elixir
alias RethinkDB.Query

conn = RethinkDB.connect

Query.db("mydb") |> Query.table("mytable") |> RethinkDB.run(conn)
```

There's an issue at #46 about specifying a db at connect, which will allow a default connection for all queries.

**Comment by hamiltop** [comment]
Database is a part of the query.

```elixir
alias RethinkDB.Query

conn = RethinkDB.connect

Query.db("mydb") |> Query.table("mytable") |> RethinkDB.run(conn)
```

There's an issue at #46 about specifying a db at connect, which will allow a default connection for all queries.

**Comment by jasdeepsingh** [comment]
Thanks so much! this was very helpful.
