### ISSUE TITLE
use RethinkDB.Connection does not inject start_link

### ISSUE THREAD

**Issue by aaron-lebo** [hamiltop/rethinkdb-elixir#54]
https://github.com/hamiltop/rethinkdb-elixir#default-connection

These docs are incorrect.

    worker(RethinkDB.Connection, [])

...works just fine. However...

    defmodule Connection do
      use RethinkDB.Connection
    end

    worker(Connection, [])

...throws an error about start_link missing.

**Comment by hamiltop** [comment]
Interesting. I'll take a look tonight. (I'm not at my machine right now).
From your example, I see a typo in Connction, any chance that same typo
exists in your code?

**Comment by hamiltop** [comment]
I think I see the problem. Not sure how that happened. I'll add a fix plus
some unit tests.

**Comment by aaron-lebo** [comment]
Thank you. I twas easy to hack around but it threw me for a loop as a new user.

**Comment by hamiltop** [comment]
Should be in.

Happy to get some more feedback!
