### ISSUE TITLE
Enum.next on a change feed is one behind

### ISSUE THREAD

**Issue by Lida** [hamiltop/rethinkdb-elixir#55]
If I type in the following in iex:
```
changes = RethinkDB.Query.table("test") |> RethinkDB.Query.changes |> RethinkDB.run(RethinkDB.connect)

Enum.each(changes, fn change -> IO.puts inspect(change["new_val"]) end)
```
It wouldn't print on the first change in the table. It would only show the first change when there is a second change.

If I use ```RethinkDB.next changes```, it would return correct on the first change.

**Comment by hamiltop** [comment]
Should be fixed in master. Thanks for the report!

**Comment by Lida** [comment]
Great! Thanks for the great lib.
