### ISSUE TITLE
Full Phoenix Example / Quick Guide required

### ISSUE THREAD

**Issue by mesosteros** [hamiltop/rethinkdb-elixir#57]
For people completely new to Phoenix, RethinkDB and Elixir, I think a very small and simple example/guide showing us all the steps from installing to querying in our project, but with all small details like where to put the connection (which module/function/file). The database is created directly using the RethinkDB interface or the Phoenix/rethinkdb adapter? How to create a table and validate that it exists, how to insert/update/delete through queries.
Also, you should add the hex package to the README when it comes to installing rethinkdb-elixir in mix.exs.
At this point I serve RethinkDB from a Linux Ubuntu VM, and I have a Phoenix Project in Windows which is the host to the Virtual Box VM. I can connect to the RethinkDB web GUI on Windows through the 8080 port in my browser (192.168.1.69:8080).
Shouldn't I put the name of my database to connect to somewhere?

**Comment by hamiltop** [comment]
lots of issues listed here, I'll address them one by one:

1. Example for Phoenix, RethinkDB, Elixir. This is a bit beyond the scope of the work I'm doing. As I discussed with @linicks in https://github.com/hamiltop/rethinkdb-elixir/issues/31 I'm happy to help anyone who wishes to provide better documentation. My priority, however, is getting the library to a code complete stage (there are still a number of parts of the query language missing, as well as a lot of work that needs to be done around connections).
2. Creating tables: The query language supports creating tables. Best practice has yet to be determined. We don't have any sort of migration framework at the moment. I would suggest researching how it is done in other languages (ruby seems to be a good reference) and reporting back here.
3. Hex package: I'm planning to release a new hex package (0.1.0) once the full query language is implemented. Until then, using a git checkout of master is the best bet.
4. Name of the database: https://github.com/hamiltop/rethinkdb-elixir/issues/46 was filed a while ago. Until that is addressed, `db("db_name") |> table("table_name")` will do the trick.

**Comment by mesosteros** [comment]
I finally managed to do it.
1) Create a new phoenix project without ecto:
```mix phoenix.new rethinkTest --no-ecto```
2) Add the package to mix.exs:
```
defp deps do
  [{:phoenix, "~> 0.13.1"},
   {:phoenix_html, "~> 1.0"},
   {:phoenix_live_reload, "~> 0.4", only: :dev},
   {:rethinkdb, "~> 0.0.5"},
   {:cowboy, "~> 1.0"}]
end
```
3) Run ```mix deps.get``` to install the package in the project.
4) Create a file in /web (e.g. database.ex) and place the following code in it:
```defmodule RethinkTest.Database do
  use RethinkDB.Connection
end```
5) Add the following worker to your children array in ```/lib/rethinkTest.ex``` file:
```worker(RethinkDB.Connection, [[name: RethinkTest.Database, host: '192.168.1.69', port: 28015]])```
6) To execute queries you can either:
6.1) Add them to a controller module
6.2) Add them to /priv/migrations/your_database_operation_name.exs and run the file with ```mix run priv/migrations/your_database_operation_name.exs```
7) Example in the page_controller.ex module, inside the index function
```table_create("people")
    |> RethinkTest.Database.run
    |> IO.inspect

    table("people")
    |> insert(%{first_name: "John", last_name: "Smith"})
    |> RethinkTest.Database.run
    |> IO.inspect

    table("people")
    |> RethinkTest.Database.run
    |> IO.inspect
    render conn, "index.html"
```
