### ISSUE TITLE
Getting success message on query such as insert

### ISSUE THREAD

**Issue by mesosteros** [hamiltop/rethinkdb-elixir#59]
What does a query such as insert return in order to evaluate success/error? 
I want to evaluate if the insert was successful so I can use in my flash messages in Phoenix.

**Comment by hamiltop** [comment]
You will get something like:

```
%RethinkDB.Record{data: %{"deleted" => 0, "errors" => 0, "generated_keys" => ["15cc4e19-fc72-4c19-b3a5-47141b6a63e0"], "inserted" => 1, "replaced" => 0, "skipped" => 0, "unchanged" => 0}}
```

On failure, you will get something like:

```
%RethinkDB.Response{data: %{"b" => [0], "n" => [], "r" => ["Table `test.oops` does not exist."], "t" => 18}, token: <<5, 0, 0, 0, 0, 0, 0, 0>>}
```

Eventually, errors will be more explicit exceptions, see https://github.com/hamiltop/rethinkdb-elixir/issues/41

**Comment by sikanhe** [comment]
can you give an example on how you would handle success/error on a query?

**Comment by hamiltop** [comment]
What do you mean? My previous comment gives an example.

**Comment by sikanhe** [comment]
I'm trying to find what's the best way to pattern match against the response, i am still new to elixir pattern matching style, i know i can if response.data.inserted > 0 but there is gotta be a better way

**Comment by sikanhe** [comment]
ah i figured it out, 

    case response.data do
      %{"errors": 0} -> text conn, "success"
      _-> text conn, "failed"
    end
