### ISSUE TITLE
Example apps

### ISSUE THREAD

**Issue by AdamBrodzinski** [hamiltop/rethinkdb-elixir#63]
I'm new to Elixir & have spent several hours trying to get this to work with Phoenix or Maru.

It would be really nice to have some kind of an example app(s) to start with that has a basic CRUD layout. Even links in the wiki to other public examples would be most helpful.

I fought through numerous errors by following this [SO post](http://stackoverflow.com/questions/31457945/how-to-use-rethinkdb-with-phoenixframework) (which I am most grateful for) and I finally have a working app with the latest rethinkdb-elixir and Phoenix.

I would be more than happy to share a repo/link if that's something you're interested in linking to/including. It's just a basic crud example in Phoenix to print out the result of the db query (no HTML)

I noticed the 10 min guide and was super bummed it wasn't filled out :smile: 

BTW, thanks for putting all your effort into this! Using Elixir + Rethink provides such a nice way to get data from the database.

**Comment by hamiltop** [comment]
This is the easiest way to say thank you, to provide example repos and links. Let's make a section in the Wiki for example apps and the nlink to the one you've built.

**Comment by AdamBrodzinski** [comment]
Awesome, will do! I'm going to re-do it this week-ish & leave meaningful commits for the actual Rethink changes along with a readme on all the exact steps on how to produce it (including using curl).

Is the 10min guide something that already has code written for it? The paragraphs seem like someone has already figured out what to put there? At any rate i'd be more than happy to fill it in and help keep it up to date if that's something you'd want to do.

I'm starting my Elixir adventure with a Phoenix app for an upcoming internal dashboard app and hope to eventually migrate my other apps over once it makes sense so i'll be watching for any breaking changes anyhow.

**Comment by hamiltop** [comment]
https://github.com/hamiltop/rethinkdb-elixir/issues/58 There's the latest on the ten minute guide.

**Comment by AdamBrodzinski** [comment]
@hamiltop Just added an example repo and wiki section for example apps. When you have a spare moment i'd really appreciate a 2nd look so I don't teach the wrong thing! 

- [setup commit](https://github.com/AdamBrodzinski/phoenix-rethinkdb-example/commit/87baefadaa919e34ae14d85a7cdc7f73b72eb3c1)
- [query commit](https://github.com/AdamBrodzinski/phoenix-rethinkdb-example/commit/6d069c11a9f3fdd413a1385ad9fe9c740e10a25a)

`json` is conflicting (error below) so I ended up returning: `Phoenix.Controller.json` and that seemed to work ok. However `RethinkDB.Query` fails. How should one return JSON for the response?

`json/2 imported from both RethinkDB.Query and Phoenix.Controller, call is ambiguous`

**Comment by hamiltop** [comment]
So a lot of my examples are meant to be super convenient. `json` is a part
of the RethinkDB query language and it looks like you are importing
everything. The more correct approach is to import only the functions you
are using. Alternatively you can exclude json.

Instead of `use RethinkDB` (which is just a convenience macro to import
everything fro RethinkDB and RethinkDB.Query) do:

```
import RethinkDB.Query, only: [table: 1, insert: 2]
```

I'll make some more comments on the commits themselves.

See
http://elixir-lang.org/getting-started/alias-require-and-import.html#import
for more information.

**Comment by AdamBrodzinski** [comment]
Thanks @hamiltop !! :beers: I just pushed up those changes.

I think most of the confusion is from the lack of my Elixir experience, i've only been tinkering with it for a few weekends :smile:
