### ISSUE TITLE
ReQL get_all() index option

### ISSUE THREAD

**Issue by almightycouch** [hamiltop/rethinkdb-elixir#65]
I'm trying to run following query:

```js
r.table("albums").getAll("c296e10c-110a-4103-9e77-47bfebb7fb2e", {index:'artist_mbid'})
```

This his how my query looks like in Elixir:

```elixir
table("albums")
|> get_all(["c296e10c-110a-4103-9e77-47bfebb7fb2e"], %{index: "artist_mbid"})
```

If i use an existing primary key from the table, `get_all` works fine. But when i try to use a different `:index`, my query fails (return an empty set).

**Comment by hamiltop** [comment]
Fixed, in master now.

Thanks for reporting! I try to fix bugs like this ASAP (I pushed the fix last night but forgot to respond here), so if you see anything else please let me know.

**Comment by hamiltop** [comment]
Also released new version on hex (includes updated connection handling too)

**Comment by almightycouch** [comment]
Thanks for fixing and deploying so fast.

I know it's off-topic but i wanted to ask why maps are used to pass options and not keywords.
I thought keywords where the way to go for passing options (with that syntactic sugar) in Elixir:

```elixir
get_all(["..."], index: "artist_mbid")
```

**Comment by hamiltop** [comment]
Keywords are pretty legacy. Before erlang 17 maps didn't exist, and until erlang 18 maps were slow. So most of the standard library expects property lists instead of maps.

I'll take a look to see if supporting keywords is difficult.

**Comment by almightycouch** [comment]
Ok, wasn't aware of that. I'm pretty new to Elixir and the Erlang world.

From what i saw in examples and frameworks, keywords are used mostly for passing options to functions.
Normally only a few options are passed (<10). So this shouldn't impact performances much.

**Comment by hamiltop** [comment]
The complexity here is functions like `index_status` where you can call it like: `index_status(table)` (get the status for all indexes) or `index_status(table, indexes)` (get the status for provided indexes). If you allow keyword opts, then `index_status(table, foo: true)` is really `index_status(table, [{:foo, true}])` and then we either have an index named `{:foo, true}` or we have a the options `foo` set to true. Semantically it's easy to see which is correct and in this particular case, `index_status` doesn't accept options. However I would need to check for all query functions for similar ambiguities. Maps are much simpler to differentiate.

I'll put up a branch with keyword opts support if you want to help test it out. It may be that any ambiguous cases are non-issues like `index_status`.

**Comment by almightycouch** [comment]
> I'll put up a branch with keyword opts support if you want to help test it out. It may be that any ambiguous cases are non-issues like index_status.

Glad to help you here.

**Comment by hamiltop** [comment]
Captured in https://github.com/hamiltop/rethinkdb-elixir/issues/66
