### ISSUE TITLE
Record validation with rethinkdb-elixir

### ISSUE THREAD

**Issue by AdamBrodzinski** [hamiltop/rethinkdb-elixir#70]
I'm starting to build up a new app using this drive and was wondering how I should handle validating POST data coming in from the server. I'm using Phoenix and the defacto seems to be to use Ecto.

I'm new to Elixir and am not sure if there are things in the eco-system that are already there to accomplish this. My first thought was to manually filter and cast types as needed and then do a pattern match to check that the required keys are there.

I also ran across some issues stating that Ecto could be used without persistence but it's unclear how one would do that.

If you could shed any light on this and/or your opinion on how you would tackle it, I would greatly appreciate it!!

**Comment by hamiltop** [comment]
This ties in with https://github.com/hamiltop/rethinkdb-elixir/issues/45 and a bit of exploration is needed.

My guess is that `Ecto.Model` will work out of the box and then we just need a to create a little macro shim to parse to and from RethinkDB queries and results.

**Comment by hamiltop** [comment]
Taking a closer look, Ecto.Model jives fairly well. Validations and changesets will work out of the box. Hooks will not.

**Comment by hamiltop** [comment]
An example of using Ecto validations with RethinkDB. Given a model:

```elixir
defmodule User do
  use Ecto.Model

  schema "users" do
    field :name
    field :email
    field :age, :integer
  end

  def changeset(user, params \\ :empty) do
    user
    |> cast(params, ~w(name email), ~w(age))
    |> validate_format(:email, ~r/@/)
    |> validate_inclusion(:age, 18..100)
    |> unique_constraint(:email)
  end
end
```

Insert with validations:
```elixir
iex(38)> changeset = User.changeset(%User{}, %{age: 0, email: "mary@example.com"})
...

iex(39)> changeset.errors
[age: "is invalid", name: "can't be blank"]

iex(40)>  changeset = User.changeset(%User{}, %{age: 21, name: "Mary", email: "mary@example.com"})
...

iex(41)> changeset.errors
[]

iex(46)> data = Ecto.Changeset.apply_changes(changeset) |> Map.from_struct |> Map.delete(:__meta__) |> Map.delete(:id)
%{age: 21, email: "mary@example.com", name: "Mary"}

iex(47)> table("users") |> insert(data) |> Friends.Database.run
%RethinkDB.Record{data: %{"deleted" => 0, "errors" => 0,
   "generated_keys" => ["76494da0-33c0-498d-a813-a475c39e6332"],
   "inserted" => 1, "replaced" => 0, "skipped" => 0, "unchanged" => 0}}

```

Update with validations:
```elixir
iex(52)> %Record{data: data} = table("users") |> get("76494da0-33c0-498d-a813-a475c39e6332") |> run
%RethinkDB.Record{data: %{"age" => 21, "email" => "mary@example.com",
   "id" => "76494da0-33c0-498d-a813-a475c39e6332", "name" => "Mary"}}

iex(55)> u = struct(User, Enum.map(data, fn {k,v} -> {String.to_existing_atom(k), v} end))
%User{__meta__: #Ecto.Schema.Metadata<:built>, age: 21,
 email: "mary@example.com", id: "76494da0-33c0-498d-a813-a475c39e6332",
 name: "Mary"}

iex(58)> changeset = User.changeset(u, %{email: "dummy"})
...

iex(59)> changeset.errors
[email: "has invalid format"]

iex(60)> changeset = User.changeset(u, %{email: "other_mary@example.com"})
...

iex(61)> changeset.errors
[]

iex(62)> data = Ecto.Changeset.apply_changes(changeset) |> Map.from_struct |> Map.delete(:__meta__)
%{age: 21, email: "other_mary@example.com",
  id: "76494da0-33c0-498d-a813-a475c39e6332", name: "Mary"}

iex(63)> table("users") |> get(data.id) |> update(data) |> run
%RethinkDB.Record{data: %{"deleted" => 0, "errors" => 0, "inserted" => 0,
   "replaced" => 1, "skipped" => 0, "unchanged" => 0}}

```

So there's a good example. A few clumsy pieces:

1. We delete `id` from the result of `apply_changes` if it's nil (which isn't the case when updating). This is because RethinkDB will treat nil as an incorrect id.
2. Converting from a map with string keys to a struct is clumsy and will raise and error if extra fields exist (because they aren't exisitng atoms).

The first one is a little clumsy but not terribly obscure. The error message is pretty clear.

The second one is something we need to take care of and is captured in https://github.com/hamiltop/rethinkdb-elixir/issues/45

Callbacks is another beast, but they can explicitly be called like in `Ecto.Model.Callbacks.__apply__ User, :before_delete, changeset`

I think there might be some value in a `rethinkdb_ecto` shim of sorts, which will reduce boilerplate. However, I don't want to bring Ecto itself into this library. Alternatively, someone could create an Ecto Adapter for RethinkDB (which I'm not terribly interested in doing, especially since Ecto.Query isn't going to offer much over the native query functions and will likely just introduce more bugs due to complexity).

**Comment by AdamBrodzinski** [comment]
Oh wow thanks for all the help!! I was also tinkering with Ecto and was able to get the changeset validation working(ish) but did not get to the `apply_changes` to extract the data. This is great!

I agree that a full Ecto adapter doesn't make sense (and wouldn't want to use it's query syntax). For my use case it would be nice to basically validate data coming in the API without re-inventing the wheel. With that in mind making a little helper function for myself will do the trick.

I'm not sure if providing a built in insert helper would be bloat/feature-creep but it would be handy for Phoenix users if there is struct support from #45 .  It would be awesome to just do a: 
`table("posts") |> insert(changeset) |> Example.Database.run`

Thanks again! Once I can get something ironed out i'll add an Ecto branch to my phoenix example repo too.

**Comment by AdamBrodzinski** [comment]
Feel free to open this back up if it's helpful.

**Comment by hamiltop** [comment]
@AdamBrodzinski Can you take a bit of time and play with https://github.com/hamiltop/rethinkdb_ecto ? It's super minimal, but I think it accomplishes what we want. It should support all the callbacks and validation goodness you want.

**Comment by AdamBrodzinski** [comment]
Absolutely! This is perfect timing too... last weekend I started porting an API app over to Phoenix and Rethink to try and learn Elixir and Phoenix better... I started to make a think adapter but this looks *great*!

I'll start tinkering with it today and will mostly get into it tomorrow. 

Once I get the hang of everything and it stabilizes I want to write a blog post and perhaps a screencast for a small crud app using Rethink :smiley:
