### ISSUE TITLE
Basic query

### ISSUE THREAD

**Issue by mindeavor** [hamiltop/rethinkdb-elixir#75]
I'm trying to perform a basic insert query:

```elixir
response = Query.db('my_app_dev')
|> Query.table('rooms')
|> Query.insert([%{ name: 'lobby' }])
|> MyDB.run
```

But the response I get is:

```
%RethinkDB.Response{data: %{"b" => [0, 0, 0], "e" => 3000000, "n" => [], "r" => ["Expected type STRING but found ARRAY."], "t" => 18}, token: <<0, 0, 0, 0, 0, 0, 0, 0>>}
```

The connection module is set up like so:

```elixir
defmodule MyDB do
  use RethinkDB.Connection
end
```

With a worker defined right below the default endpoint supervisor:

```
children = [
  supervisor(MyApp.Endpoint, []),
  worker(MyDB, [])
]
```

And the database and table certainly exist (I can see them in RethinkDB's admin panel on http://localhost:8080/).

Am I doing something wrong? Hopefully it's a simple mistake.

**Comment by hamiltop** [comment]
We only support binary strings `"my_app_dev"`, not charlists `'my_app_dev'`. Switch everything to double quotes and everything should be good.

**Comment by mindeavor** [comment]
That worked! Thank you very much :)
