### ISSUE TITLE
Database name for a default connection

### ISSUE THREAD

**Issue by ianwalter** [hamiltop/rethinkdb-elixir#79]
I'm trying to follow this:

> This connection can be supervised without a name (it will assume the module as the name).

But what is the name? If the module name is `FooDatabase`, is the database called `FooDatabase`? or is it `foo_database`? I tried both and neither worked. It keeps falling back to the database name `test`. 

I think the ability to explicitly set the name would be more straight-forward.

**Comment by hamiltop** [comment]
Are you well versed in Elixir/Erlang, including named processes and
supervising trees? I think you may be confusing concepts here. I'm happy to
correct misleading documentation, but I need to understand to context in
which it was confusing.

**Comment by ianwalter** [comment]
Sorry, I did confuse those concepts. I thought the name was referring to the name of the database. It would be nice if you didn't have to specify the database on each query (if you have multiple databases on a server). Maybe there could be a way to specify it in the default connection module. Thanks for your help.

**Comment by hamiltop** [comment]
That is supported. See http://hexdocs.pm/rethinkdb/RethinkDB.Connection.html#start_link/1

I will add that link to the README

**Comment by hamiltop** [comment]
README updated. Is it clear enough now?

**Comment by AdamBrodzinski** [comment]
@hamiltop this is much better. I also didn't realize that the db and auth key could be configured there.

Thanks!!

**Comment by ianwalter** [comment]
Yes, thank you.
