### ISSUE TITLE
Default connection connecting to wrong database

### ISSUE THREAD

**Issue by ryanswapp** [hamiltop/rethinkdb-elixir#80]
Hello,

I've had some extra time this week and decided to play around with the default connection feature. I seem to have run into a bit of a problem. The default connection appears to always be looking for the 'test' database and does not infer the database name from the database module. Here is my code:

Database Module
```
defmodule RethinkYourDataDatabase do 
	use RethinkDB.Connection
end
```
Worker
```
worker(RethinkYourDataDatabase, [[port: 28015, host: 'localhost']]),
```
I have a database named RethinkYourDataDatabase in the RethinkDB admin panel that I assumed this setup would connect to. However, when I run a query like this:
```
q = table("posts") |> DB.run()
```
I get the following response:
```
%RethinkDB.Response{data: %{"b" => [], "e" => 4100000,
   "r" => ["Database `test` does not exist."], "t" => 18},
 token: <<0, 0, 0, 0, 0, 0, 0, 0>>}
```
Any ideas as to what is going on?

**Comment by hamiltop** [comment]
The reason it's using the `test` database is because you didn't specify a database.

> I have a database named RethinkYourDataDatabase in the RethinkDB admin panel that I assumed this setup would connect to.

I'm not sure where that assumption is coming from. For what it's worth, you are the second person this week to make that assumption.

See https://github.com/hamiltop/rethinkdb-elixir/issues/79

I have the same question for you:

> Are you well versed in Elixir/Erlang, including named processes and
supervising trees? I think you may be confusing concepts here. I'm happy to
correct misleading documentation, but I need to understand to context in
which it was confusing.

Sorry for being terse. I'm trying to understand exactly what is confusing here so I can clarify it.

**Comment by ryanswapp** [comment]
> Sorry for being terse.

No worries man. I'm not trying to be difficult and I apologize if that's how it came across.

In the README under the Default Connection heading it says:

> This connection can be supervised without a name (it will assume the module as the name).

I think I may be misinterpreting how the package works. I was under the impression that the 'name' option passed to the worker was the name of the database that I want to connect to. However, because I'm using the default connection feature an error is thrown if I try to pass a 'name' option to the worker. 

Sorry for the noob question but how do I tell the package what database I'd like to use?

**Comment by ryanswapp** [comment]
Ahh nevermind. I see the options here http://hexdocs.pm/rethinkdb/RethinkDB.Connection.html#start_link/1 

Sorry about the confusion.

**Comment by hamiltop** [comment]
So this confusion I believe is tied to inexperience with erlang/elixir.

> This connection can be supervised without a name (it will assume the module as the name).

That means that in the supervision tree, the connection process will take the module as the name. See http://elixir-lang.org/docs/v1.1/elixir/GenServer.html under the section `Name Registration` for a good explanation.

It's also explained in great detail in the Getting Started guide on elixir-lang.org as well as the book Programming Elixir.

This is not being critical of your approach to learning. This is a big breakdown in how the community is presented to newcomers and I'd like to know how we can better serve these people.

**Comment by ryanswapp** [comment]
Ya I am definitely inexperienced when it comes to erlang/elixir. I think where I went wrong was that something made me think that the 'name' option was how you would select which DB to use. I'm aware of the fact that you can name processes, I was just assuming that the default connection feature would infer the name of the database from the module name. 

This may be a terrible idea as it's just off the top of my head, but what if you required users to set a db name? I think it may be confusing that it just automatically connects to the test database without giving some kind of warning.

**Comment by hamiltop** [comment]
Inferring the name of the database from the module name puts some odd constraints and conventions on your database names.

The current behaviour matches that of the official drivers. Also, the default connection was one of the later pieces I implemented. Neither of those are good reasons not to do so, but just an explanation of why it is what it is.

I see a few use cases:

1. Using a single db for all queries.
2. Using multiple dbs for various queries.

The implementation options are:

1. require a db in start_link
2. if a db is not provided, require a db in queries
3. current behavior

The problem with the first one is that it puts use case number 2 in an awkward spot.
The problem with the second one is that the Rethink protocol doesn't require a db and will assume 'test' if none is provided. To implement this purely client side would be difficult.
The problem with the current behavior is the confusion you've experienced.

None of these seem to be without drawbacks, and the advantage of the current behavior is that it matches rethinkdb behavior elsewhere.
