### ISSUE TITLE
Changefeed example?

### ISSUE THREAD

**Issue by skosch** [hamiltop/rethinkdb-elixir#84]
Hi,

thanks for this fantastic set of modules!

I'm trying to get a `RethinkDB.Changefeed` going – specifically, I'm following your example (see below) but on trying to get this module to run as a supervised worker I get an error saying `start_link/3` can't be found ... presumably because the `__using__` macro doesn't actually import anything but only calls `@behaviour`? (I'm only a few hours into Elixir, so I'm not sure what I'm talking about :)

I'd be really grateful for a somewhat more fleshed-out example of how to get a supervised changefeed to run (and maybe how to use GenEvent callbacks to broadcast messages down Phoenix channels ... but that I can probably figure out myself too).

Thanks again!

```elixir
defmodule App.UsersFeed do
  use RethinkDB.Changefeed

  def init(opts) do
    IO.inspect __info__(:functions)
    gen_event = Dict.get(opts, :gen_event)
    db = Dict.get(opts, :db)
    query = RethinkDB.Query.table("users")
      |> RethinkDB.Query.changes
    {:subscribe, query, db, gen_event}
  end

  def handle_update(data, gen_event) do
    Enum.each(data, fn
      # no `old_val` means a new entry was created
      %{"new_val" => val, "old_val" => nil}, acc ->
        GenEvent.notify(gen_event,{:create, val})
      # no `new_val` means an entry was deleted
      %{"new_val" => nil, "old_val" => val}, acc ->
        GenEvent.notify(gen_event,{:delete, val})
      # otherwise, we have an update
      %{"new_val" => val, "old_val" => old_val}, acc ->
        GenEvent.notify(gen_event,{:update, old_val, val})
    end)
    {:next, gen_event}
  end
end
```

**Comment by hamiltop** [comment]
The normal pattern with behaviours (see GenServer for another example) is to provide a `start_link` that accepts the module implementing the behaviour as the first argument.

So in your case, what you want to call is `RethinkDB.Changefeed.start_link(App.UsersFeed, opts, gen_server_opts)`

See https://github.com/hamiltop/friends-demo/blob/master/lib/friends/followers_changefeed.ex#L9 for a more in depth example.

In that example, I define a `start_link` that hardcodes the module to `__MODULE__`.

**Comment by hamiltop** [comment]
There are actually a bunch of different changfeeds in that example app:

https://github.com/hamiltop/friends-demo/blob/master/lib/friends/followers_changefeed.ex
https://github.com/hamiltop/friends-demo/blob/master/lib/friends/leaderboard_changefeed.ex
https://github.com/hamiltop/friends-demo/blob/master/lib/friends/people_changefeed.ex
https://github.com/hamiltop/friends-demo/blob/master/lib/friends/person_changefeed.ex

**Comment by skosch** [comment]
Ah, perfect! Somehow I missed that demo code entirely. I'm adding a link to the list of examples if you don't mind.

Thanks again Peter!
