### ISSUE TITLE
Changefeed async `:next`

### ISSUE THREAD

**Issue by hamiltop** [hamiltop/rethinkdb-elixir#85]
Let's talk about backpressure. Changefeeds in RethinkDB have a backpressure mechanism built in. It only sends data if requested. After data is sent, it must be requested again.

There are situations that would benefit from being able to delay requesting more data. Currently you can just call `:timer.sleep` or some other blocking call (like kicking off a query to the DB) and when it returns, `handle_update` will complete and return. This effectively provides backpressure, but it isn't quite the "best" way to approach this.

A more correct way to handle this is to kick off the DB call from it's own process and have that process send a message back to the Changefeed process once the call completes.

To illustrate, here's how one would do this in a simple GenServer:

```elixir
defmodule Example do
  use GenServer

  def handle_call(msg, from, state) do
    task = Task.async fn ->
      :timer.sleep(1000)
      "Done"
    end
    {:noreply, {from, task}}
  end

  def handle_info({ref, msg}, {target, %Task{ref: ref}}) do
    GenServer.reply(target, msg)
    {:noreply, nil}
  end
end
```

How does this differ from just calling `:timer.sleep` in `handle_call` and then returning `{:reply, "Done", nil}`? During that 1000ms, the async GenServer can accept messages. This includes system messages, which makes using `:observer` and other tools so much easier.

I would like to mimic this API.

Some ideas:

1. Allow `handle_update` to return `{:noreply, state}`. `handle_cast` and `handle_info` can return `{:next, state}` and `handle_call` can return either `{:next, reply, state}` or `{:next, state}` (mirroring the `:reply` and `:noreply` that already exists). returning `:next` would request the next set of updates.
2. Allow `handle_update` to return `{:pause, state}`. `handle_cast`/`handle_call`/`handle_info` can call `Changefeed.resume(pid)` to resume the feed.

**Comment by thelinuxlich** [comment]
There is also the squash option on changefeeds

**Comment by hamiltop** [comment]
Squash is sort of orthogonal. This entirely client behavior being discussed here. Any squashed option value could benefit from these changes.

To expand, squash is about what the server should do if changes are not requested fast enough. This proposal is about how the client should intentionally delay requesting more changes.

**Comment by hamiltop** [comment]
I think I'm going to move this to https://github.com/hamiltop/rethinkdb_changefeed

**Comment by thelinuxlich** [comment]
Why a separate module?

**Comment by hamiltop** [comment]
I want to be able to independently version the Changefeed module. It isn't tightly coupled to the driver and I want to be able to make breaking changes without having to bump the driver version.

**Comment by hamiltop** [comment]
Closing in favor of https://github.com/hamiltop/rethinkdb_changefeed/issues/1
