### ISSUE TITLE
Where table creation should be specified?

### ISSUE THREAD

**Issue by sobolevn** [hamiltop/rethinkdb-elixir#97]
Hello! Firstly, thanks for your project. 

I have faced a problem, I don't know where to place table creation. I have looked through the examples and articles in the wiki, but all of them assume that I have already created everything via the web interface.

Surely, it is the easiest way to go. But I love to automate things. How this can be achieved with migrations or something similar. Maybe a separate mix task?

PS. Maybe it is a good idea to create `rethinkdb-elixir` tag on SO? And list it in the `README` for the future use. I can ask this question there with the appropriate tag.

**Comment by hamiltop** [comment]
I think this is covered in https://github.com/hamiltop/rethinkdb_ecto/issues/13

If you don't want to use a migration framework, just a simple script under a `/scripts` dir would suffice. Call it with `mix run scripts/migrations`.
