### ISSUE TITLE
ReQL get_all with compound indexes

### ISSUE THREAD

**Issue by rksasaki** [hamiltop/rethinkdb-elixir#98]
Hi!

I'm trying to run the following query:
` table("profiles") |> get_all(["company_xxx",1], %{index: "active_profiles"})`

Single indexes seems to work fine, but when I try to use a compound index it returns an empty set.

**Comment by hamiltop** [comment]
Is the key you are trying to fetch `["company_xxx", 1]` or is it two keys, `"company_xxx"` and `1`?

Get_all expects a list of keys, so maybe you need to wrap it in another set of []?

**Comment by hamiltop** [comment]
@rksasaki Any more information here?

**Comment by ptgamr** [comment]
+1 to this. compound index does not return result for me when `get_all`

**Comment by hamiltop** [comment]
Can you get it working in JavaScript and then paste the query in here? That's the easiest way to fix it for me.

**Comment by ptgamr** [comment]
@hamiltop 

I create a compound index using Elixir:
```
Query.index_create("uniqueness", Lambda.lambda fn(row) -> [row["type"], row["externalId"], row["source"]] end)
```

The get_all in Elixir version does not return me result
```
Query.get_all([mapping[:type], mapping[:externalId], mapping[:source]], %{:index => "uniqueness"})
```

However, the data explorer does have result
```
r.db('databaseName').table('tableName').getAll(['player', '2166', 'shl'], {index: "uniqueness"})
```

**Comment by hamiltop** [comment]
Cool I'll take a look.

**Comment by hamiltop** [comment]
Can you try a double array? `get_all([['player', '2166', 'shl']])`

One limitation we have in Elixir is that we don't support varargs. So in JavaScript you would do `.getAll(key1, key2, {index: "uniqueness"})`. In Elixir we have to do `getAll([key1, key2], index: "uniqueness")`. With a single key it becomes `getAll([key1], index: "uniqueness")` and when `key1` is `[partA, partB]` you have to do `getAll([[partA, partB]], index: "uniqueness")`

**Comment by ptgamr** [comment]
@hamiltop thanks! it works!

**Comment by ptgamr** [comment]
@hamiltop I think it would be useful if this appear in the README file. I've just created a PR for that.
